name: Java CI with Maven (Docker)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-java-app .

      - name: Package Maven Project (inside container)
        run: docker run --rm my-java-app mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-java-app .

      - name: Run Unit Tests (inside container)
        run: docker run --rm my-java-app mvn test
        # ggggg
