name: Java CI with Maven (Docker)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-image-tag.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set Docker image tag
        id: set-image-tag
        run: echo "::set-output name=image-tag::my-java-app:${{ github.sha }}"

      - name: Build Docker image
        run: docker build -t my-java-app:${{ github.sha }} .

  build:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Run mvn package in Docker
        run: docker run --rm my-java-app:${{ github.sha }} mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run mvn test in Docker
        run: docker run --rm my-java-app:${{ github.sha }} mvn test
